vich_uploader:
    db_driver: orm

    mappings:
        profil_image_student:
            uri_prefix: /images/profil_student
            upload_destination: '%kernel.project_dir%/public/images/profil_student'
            namer : Vich\UploaderBundle\Naming\UniqidNamer

        profil_image_company:
            uri_prefix: /images/profil_company
            upload_destination: '%kernel.project_dir%/public/images/profil_company'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        profil_image_school:
            uri_prefix: /images/profil_school
            upload_destination: '%kernel.project_dir%/public/images/profil_school'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
